apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  name: prodref01-xdds6-infra-us-east-2a
  namespace: openshift-machine-api
  labels:
    machine.openshift.io/cluster-api-cluster: "prodref01-xdds6"
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: "prodref01-xdds6"
      machine.openshift.io/cluster-api-machineset: prodref01-xdds6-infra-us-east-2a
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: "prodref01-xdds6"
        machine.openshift.io/cluster-api-machine-role: infra
        machine.openshift.io/cluster-api-machine-type: infra
        machine.openshift.io/cluster-api-machineset: prodref01-xdds6-infra-us-east-2a
    spec:
      taints:
      - effect: NoSchedule
        key: infra
        value: reserved
      - effect: NoExecute
        key: infra
        value: reserved
      metadata:
        labels:
          node-role.kubernetes.io/infra: ""
      providerSpec:
        value:
          apiVersion: awsprovider.openshift.io/v1beta1
          credentialsSecret:
            name: aws-cloud-credentials
          kind: AWSMachineProviderSpec
          userDataSecret:
            name: worker-user-data
          placement:
            availabilityZone: us-east-2a
            region: us-east-2
          instanceType: m5.xlarge
          blockDevices:
          - ebs:
            iops: 0
            volumeSize: 120
            volumeType: gp2
          ami:
            id: ami-0a1f868ad58ea59a7
          subnet:
            filters:
            - name: tag:Name
              values:
              - prodref01-xdds6-private-us-east-2a
          iamInstanceProfile:
            id: prodref01-xdds6-worker-profile
          securityGroups:
          - filters:
            - name: tag:Name
              values:
              - prodref01-xdds6-worker-sg
          tags:
          - name: kubernetes.io/cluster/prodref01-xdds6
            value: owned
---
apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  name: prodref01-xdds6-infra-us-east-2b
  namespace: openshift-machine-api
  labels:
    machine.openshift.io/cluster-api-cluster: "prodref01-xdds6"
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: "prodref01-xdds6"
      machine.openshift.io/cluster-api-machineset: prodref01-xdds6-infra-us-east-2b
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: "prodref01-xdds6"
        machine.openshift.io/cluster-api-machine-role: infra
        machine.openshift.io/cluster-api-machine-type: infra
        machine.openshift.io/cluster-api-machineset: prodref01-xdds6-infra-us-east-2b
    spec:
      taints:
      - effect: NoSchedule
        key: infra
        value: reserved
      - effect: NoExecute
        key: infra
        value: reserved
      metadata:
        labels:
          node-role.kubernetes.io/infra: ""
      providerSpec:
        value:
          apiVersion: awsprovider.openshift.io/v1beta1
          credentialsSecret:
            name: aws-cloud-credentials
          kind: AWSMachineProviderSpec
          userDataSecret:
            name: worker-user-data
          placement:
            availabilityZone: us-east-2b
            region: us-east-2
          instanceType: m5.xlarge
          blockDevices:
          - ebs:
            iops: 0
            volumeSize: 120
            volumeType: gp2
          ami:
            id: ami-0a1f868ad58ea59a7
          subnet:
            filters:
            - name: tag:Name
              values:
              - prodref01-xdds6-private-us-east-2b
          iamInstanceProfile:
            id: prodref01-xdds6-worker-profile
          securityGroups:
          - filters:
            - name: tag:Name
              values:
              - prodref01-xdds6-worker-sg
          tags:
          - name: kubernetes.io/cluster/prodref01-xdds6
            value: owned
---
apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  name: prodref01-xdds6-infra-us-east-2c
  namespace: openshift-machine-api
  labels:
    machine.openshift.io/cluster-api-cluster: "prodref01-xdds6"
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: "prodref01-xdds6"
      machine.openshift.io/cluster-api-machineset: prodref01-xdds6-infra-us-east-2c
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: "prodref01-xdds6"
        machine.openshift.io/cluster-api-machine-role: infra
        machine.openshift.io/cluster-api-machine-type: infra
        machine.openshift.io/cluster-api-machineset: prodref01-xdds6-infra-us-east-2c
    spec:
      taints:
      - effect: NoSchedule
        key: infra
        value: reserved
      - effect: NoExecute
        key: infra
        value: reserved
      metadata:
        labels:
          node-role.kubernetes.io/infra: ""
      providerSpec:
        value:
          apiVersion: awsprovider.openshift.io/v1beta1
          credentialsSecret:
            name: aws-cloud-credentials
          kind: AWSMachineProviderSpec
          userDataSecret:
            name: worker-user-data
          placement:
            availabilityZone: us-east-2c
            region: us-east-2
          instanceType: m5.xlarge
          blockDevices:
          - ebs:
            iops: 0
            volumeSize: 120
            volumeType: gp2
          ami:
            id: ami-0a1f868ad58ea59a7
          subnet:
            filters:
            - name: tag:Name
              values:
              - prodref01-xdds6-private-us-east-2c
          iamInstanceProfile:
            id: prodref01-xdds6-worker-profile
          securityGroups:
          - filters:
            - name: tag:Name
              values:
              - prodref01-xdds6-worker-sg
          tags:
          - name: kubernetes.io/cluster/prodref01-xdds6
            value: owned
