apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: io2
parameters:
  encrypted: "true"
  type: io2
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
